### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by mikelward** [tidepool-org/urchin-android#1]
Brandon confirmed this codebase is intended to be licensed under two-clause BSD license.

Until my VCLA is approved, I probably shouldn't send a pull request, so filing this issue instead.

Thanks!

**Comment by mikelward** [comment]
Also for https://github.com/tidepool-org/mobile-android, if possible.  (No way to file a bug there AFAICS.)

**Comment by HowardLook** [comment]
Missing BSD License added in both places. Thanks for letting us know!
